#!/bin/bash

echo "🎯 VERIFICACIÓN FINAL DEL SISTEMA"
echo "=================================="
echo ""

echo "✅ Accede a los servicios con localhost:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 FRONTEND (Login y Tareas)"
echo "   URL: http://localhost:8081"
echo "   Usuario: admin"
echo "   Contraseña: admin"
echo ""
echo "   PASOS DE VERIFICACIÓN:"
echo "   1. Haz login con admin/admin"
echo "   2. Agrega 3-4 tareas nuevas"
echo "   3. Elimina 1-2 tareas"
echo "   4. Haz logout"
echo "   5. Vuelve a hacer login"
echo "   → Las tareas deben persisitir ✓"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📊 GRAFANA (Dashboard)"
echo "   URL: http://localhost:3000"
echo "   Usuario: admin"
echo "   Contraseña: admin"
echo ""
echo "   DASHBOARDS DISPONIBLES:"
echo "   • Microservices Monitoring (status de servicios)"
echo "   • Redis Monitoring (métricas de Redis)"
echo ""
echo "   PASOS DE VERIFICACIÓN:"
echo "   1. Abre http://localhost:3000"
echo "   2. Login con admin/admin"
echo "   3. Ve a Dashboards → Busca 'Redis'"
echo "   4. Verifica que vea gráficos con datos ✓"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📈 PROMETHEUS (Métricas)"
echo "   URL: http://localhost:9090"
echo "   SIN AUTENTICACIÓN"
echo ""
echo "   PASOS DE VERIFICACIÓN:"
echo "   1. Abre http://localhost:9090"
echo "   2. Haz click en 'Graph'"
echo "   3. Escribe: up"
echo "   4. Clickea 'Execute'"
echo "   → Deberías ver métrica 'up{job=\"prometheus\"}' = 1 ✓"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔗 ZIPKIN (Tracing Distribuido)"
echo "   URL: http://localhost:9411"
echo "   SIN AUTENTICACIÓN"
echo ""
echo "   Puedes ver trazas de requests entre servicios"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 RESUMEN DE CAMBIOS REALIZADOS:"
echo ""
echo "✓ Frontend: Nginx con proxy reverso a todos los servicios"
echo "✓ Todos API: Persistencia de tareas en Redis (no memory-cache)"
echo "✓ Prometheus: Configuración limpia, sin errores 403/404/401/500"
echo "✓ Grafana: Dashboard Redis integrado con Prometheus"
echo "✓ Port-forwarding: Todos los servicios en localhost:XXXX"
echo ""

echo "🐛 Si algo no funciona:"
echo ""
echo "Backend (tareas no persisten):"
echo "  kubectl logs deployment/todos-api -n microservices"
echo ""
echo "Grafana no carga:"
echo "  kubectl logs deployment/grafana -n microservices"
echo ""
echo "Prometheus sin datos:"
echo "  kubectl logs deployment/prometheus -n microservices"
echo ""
echo "Frontend con errores:"
echo "  kubectl logs deployment/frontend -n microservices"
echo ""
